### PR TITLE
Add deadpool support

### PR DESCRIPTION
**Pull request by franklx**
Very simple patch supporting deadpool crate.

### CODE REVIEW

**Comment by nolanderc** [comment]
Thanks! Looks good!

But before we merge: make sure that all deadpool specific imports and impls are locked behind a feature flag.

**Comment by franklx** [comment]
Locked all deadpool specific imports and imps behind ```deadpool``` feature flag.

**Comment by nolanderc** [comment]
Awesome! Thanks a lot!

**Comment by Austaras** [comment]
@franklx @nolanderc  I believe `default-features = false` should be added to `deadpool-postgres` since it will pull in unnecessary dependency?

**Comment by nolanderc** [comment]
Good point! @franklx would you mind doing the suggested change, and make a new PR?

**Pull request merged**
